services:
  backend:
    restart: "no"
    ports:
      - "8888:80"
    volumes:
      - .:/app
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command: /start-reload.sh

  db:
    restart: "no"
    ports:
      - "5442:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"
