services:
  backend:
    restart: "no"
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
      - .:/app
    build:
      context: .
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command: /start-reload.sh

  db:
    restart: "no"
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    restart: "no"
    ports:
      - "${ADMINER_PORT}:8080"
